### ISSUE TITLE
Bug: Ch05 -- calling 'toObject' with incomplete return type 'QJsonObject'

### ISSUE THREAD

**Issue by dephora** [PacktPublishing/Learn-Qt-5#3]
### entity-collections.h - line 77 

**Issue**: 
calling 'toObject' with incomplete return type 'QJsonObject' in update function

---
<img width="1028" alt="Screen Shot 2019-07-11 at 4 28 22 PM" src="https://user-images.githubusercontent.com/5777341/61083218-32719700-a3f9-11e9-981c-982d7b70b478.png">

**Comment by packt-pradeeps** [comment]
Author's reply:
It’s hard to be sure without the complete code but I suspect you need to add an `#include <QJsonObject>` statement as the compiler is complaining it doesn’t know what QJsonObject is.
